### ISSUE TITLE
RubyGems.org links to GitHub 404

### ISSUE THREAD

**Issue by pda** [rails/journey#16]
[Journey on RubyGems.org](https://rubygems.org/gems/journey) has a Homepage link pointing at http://github.com/tenderlove/journey which returns a 404. I guess it should be changed to https://github.com/rails/journey

If only I could fix this with a pull request, I would.

Thanks for the awesome software!

**Comment by andyjeffries** [comment]
There's already a pull request about it : https://github.com/rails/journey/pull/9

**Comment by ghost** [comment]
Hey, since there is already a pull request for this can you please close this issue as it's a duplicate? :)
