### ISSUE TITLE
version 1.0.2 breaks respond_with

### ISSUE THREAD

**Issue by zacksiri** [rails/journey#18]
I think something is wrong with the respond_with when using journey 1.0.2

i am having issues using backbone with rails and when i try to create a record it seems to respond to the wrong url.

ActionController::RoutingError (No route matches {:action=>"show", :controller=>"contacts", :account_id=>#<Contact id: 53, first_name: "eee", account_id: 1, created_at: "2012-02-21 08:19:20", updated_at: "2012-02-21 08:19:20", last_name: "eee", type: "Client">}):
  app/controllers/contacts_controller.rb:15:in `create'

my controller looks like this

```
def create
    respond_with current_account.contacts.create(params[:contact])
end
```

only happens with journey 1.0.2

i had to downgrade to 1.0.1 to get it working again.

**Comment by tenderlove** [comment]
Did this route work with Rails 3.1?

**Comment by jonnii** [comment]
It looks like this is similar to the problem I'm having:

https://github.com/rails/journey/commit/70d101b3386ba26ff801cec496da9c23389434aa

**Comment by zacksiri** [comment]
honestly i am not sure if it works with rails 3.1 this app started its life as 3.2.1 

is there a reason why you ask?

**Comment by alexeymuranov** [comment]
Could this be related to #27?

**Comment by schneems** [comment]
Can you confirm that this issue is still present in Journey 1.0.4, or can you close the issue?

**Comment by pixeltrix** [comment]
Closing due to lack of feedback
