### ISSUE TITLE
journey.gemspec references files that do not exist in its github repository

### ISSUE THREAD

**Issue by cablegram** [rails/journey#2]
Line 13 of journey.gemspec references the following files that do not exist in the rails/journey github repository.
- lib/journey/definition/node.rb
- lib/journey/definition/parser.rb
- lib/journey/definition/parser.y
- lib/journey/definition/parser_extras.rb
- lib/journey/definition/scanner.rb
- .gemtest

In an excerpt from bundler:

```
Using journey (1.0.0.20110902101342) from git://github.com/rails/journey (at master)
journey at C:/Rubies/Ruby187/lib/ruby/gems/1.8/bundler/gems/journey-bc37b94050c0 did not have a valid gemspec.
This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
The validation message from Rubygems was:
  ["lib/journey/definition/node.rb", "lib/journey/definition/parser.rb", "lib/journey/definition/parser.y", "lib/journey
/definition/parser_extras.rb", "lib/journey/definition/scanner.rb", ".gemtest"] are not files
```

Are there missing files in the repository or too many files named in the s.files line in the gemspec?

**Comment by sarahhodne** [comment]
I get the same error when running `bundle install` on a freshly cloned rails repo.

**Comment by tenderlove** [comment]
Should be fixed.
