### ISSUE TITLE
Version 1.0.2 changes behavior of path helpers for non-persisted models

### ISSUE THREAD

**Issue by alexeymuranov** [rails/journey#27]
Here are steps to reproduce:

``` shell
rails new test_app
cd test_app
rails generate scaffold User name:string
rake db:migrate
```

Change the beginning of **app/views/users/_form.html.erb** to:

``` erb
<div><%= user_path(@user) %></div>
<%= form_for(@user, :url => user_path(@user)) do |f| %>
...
```

(add explicit URL).

Now:

``` shell
§ rake test:functionals
Run options: 

# Running tests:

....E..

Finished tests in 0.237093s, 29.5243 tests/s, 37.9598 assertions/s.

  1) Error:
test_should_get_new(UsersControllerTest):
ActionView::Template::Error: No route matches {:action=>"show", :controller=>"users", :id=>#<User id: nil, name: nil, created_at: nil, updated_at: nil>}
...
```

This does not happen if i add `gem 'journey', '1.0.1'` to Gemfile.

**Comment by pixeltrix** [comment]
This is a duplicate of #20

**Comment by alexeymuranov** [comment]
@pixeltrix, thanks for pointing this out to me.  Is this a bug or a desired behavior?  I want to explicitly specify the url un the form using a path helper, can i do so independently of whether the model is new or has been saved?

To explain better my use case: my `@user` will be in fact an instance of a _subclass_ of `User`, so without the use of `:url` option, `form_for` will not find the url.

**Comment by pixeltrix** [comment]
Yes, it's [desired behavior](https://github.com/rails/journey/commit/70d101b3386ba26ff801cec496da9c23389434aa). If you can't use polymorphic urls just create a helper method that calls the right url helper, e.g:

``` ruby
module ApplicationHelper
  def user_form_path(user)
    user.persisted? ? user_path(user) : users_path
  end
end
```

**Comment by alexeymuranov** [comment]
Thanks for the explanation.  Wouldn't it be nice though if  `user_path(User.new)` was returning the path to submit a new user form (usually same as `users_path`)?

**Comment by alexeymuranov** [comment]
Ok, i am closing this.

I know i am not supposed to worry about machine optimization, but making a helper that treats separately the case of a new user, one would postpone to the run time what can be done in the compile time.

I will probably just set `@user_form_url` separately in `new` and `edit` actions.
