### ISSUE TITLE
extra ?id= parameter when using a SimpleDelegator

### ISSUE THREAD

**Issue by senny** [rails/journey#29]
I use `SimpleDelegator` in my application to wrap some model objects (Decorators). I noticed, that all the urls I generate using wrapped objects look like: /articles/4?id=4
I tried to figure out where to source of this id param is and locked it down to the following line in journey:

_formatter.rb:39_

``` ruby
z = Hash[options.to_a - data.to_a - route.defaults.to_a]
```

Both options and data contain the wrapped objects but ruby does not recognize it as the same object and it is then leftover in the options hash. The following irb session should illustrate the situation.

```
ruby-1.9.3-p0 :024 > class Decorator < SimpleDelegator
ruby-1.9.3-p0 :025?>   end
 => nil 
ruby-1.9.3-p0 :026 > decorator = Decorator.new('test')
 => "test" 
ruby-1.9.3-p0 :027 > [[:id, decorator]] - [[:id, decorator]]
 => [[:id, "test"]] 
```

I tried to figure out how `Array#-` is implemented but I lack the necessary C-skills to debug this one further.

**Comment by tenderlove** [comment]
Interesting.  `Array#-` basically converts the right hand side to a hash, then checks against the hash keys.  I'll rewrite the algorithm for you in pure ruby:

``` ruby
def minus left, right
  right  = Hash[right.to_ary.map { |k| [k, true] }]
  result = []

  left.each do |item|
    next if right[item]
    result << item
  end

  result
end

p minus([1, 2, 3, 4], [2, 4])
```

I'm guessing that your delegate object isn't implementing `eql?` properly.  Can you check that `decorator.eql?(decorator)` returns true?  If it returns false, then the hash lookup inside `Array#-` would fail.

**Comment by senny** [comment]
```
ruby-1.9.3-p0 :044 > decorator = Decorator.new('test')
 => "test" 
ruby-1.9.3-p0 :029 > decorator.eql?(decorator)
 => false 
```

It seems that SimpleDelegator does not implement `eql?` therefor the call is beeing delegated to the object beeing wrapped, which is not eql to a delegator.

Where do you make the leap, that the eql? method is beeing used? Hash access seems to be working with the decorated object...

```
ruby-1.9.3-p0 :044 > decorator = Decorator.new('test')
 => "test" 
ruby-1.9.3-p0 :045 > hash = {decorator => 'hash access'}
 => {"test"=>"hash access"} 
ruby-1.9.3-p0 :046 > hash[decorator]
 => "hash access" 
```

I'm just curios. I could solve the problem by implementing eql? on the decorator correctly.
