### ISSUE TITLE
How to run benchmarks?

### ISSUE THREAD

**Issue by judofyr** [rails/journey#5]
How do you run the benchmarks for Journey?

**Comment by schneems** [comment]
What exactly are you trying to measure? I don't believe there is a benchmark suite in the app. You can run

``` shell
$ time bundle exec rake
```

Multiple times and average them out if you're interested in testing out speed of code you're writing. You could also measure in the app using `Benchmark.measure {}.real` though again, you need to get a statistically significant sample size for benchmarks to be useful. 

This issue has been open for some time with no reply, can you close it or let me know if you have follow up questions to my response? 

https://github.com/rails/journey/pull/38 is one example of writing custom benchmarks.

**Comment by judofyr** [comment]
I just feels it's a little weird to start a new Rails router (where performance is one of the goals) without having a benchmark. I kinda assumed they were not pushed or something…
