### ISSUE TITLE
journey doesn't install properly

### ISSUE THREAD

**Issue by rajeshkp** [rails/journey#56]
I get the following error while running the bundler, why is it failing here

Installing journey (1.0.4) [/home/foo/.rvm/gems/ruby-1.9.3-p362@bar/specifications/erubis-2.7.0.gemspec] isn't a Gem::Specification (NilClass instead).

**Comment by pixeltrix** [comment]
@rajeshkp looks like something may be messed up in you rvm install / gemset - can you try in a clean gemset?

**Comment by pixeltrix** [comment]
Closing due to lack of feedback
