### ISSUE TITLE
assets URLs fall into own routes rules

### ISSUE THREAD

**Issue by lapenya** [rails/journey#57]
In development, on a page load, and not all but a considerable number of JS requests like: 

<pre>
/assets/app/models/i18n.js?body=1
</pre>

do not return corresponding JS asset, but they fall into my default routes rule:

<pre>
match '*all' => 'limbo#redirect_to_there'
</pre>

using JRuby + Puma + Rails 3.2.11, journey 1.0.4

**Comment by lapenya** [comment]
<pre>
"action_dispatch.request.path_parameters"=>{:controller=>"limbo", :action=>"redirect_to_there", :all=>"app/models/i18n", :format=>"js"}
</pre>

**Comment by pixeltrix** [comment]
I assume that there's an actual file at the path `/assets/app/models/i18n.js` ? If so then it may be a thread safety issue which may also explain your experience with issue #54. Does the problem go away if you enable `config.threadsafe!` and run in production mode?

**Comment by pixeltrix** [comment]
The development mode in Rails is inherently unsafe due to code reloading so there's not a lot we can do if that's the problem.

**Comment by pixeltrix** [comment]
Closing due to lack of feedback
