### ISSUE TITLE
Add License information to gemfile

### ISSUE THREAD

**Issue by coreyhaines** [rails/journey#71]
This will make it show up on rubygems.org. I'm doing due diligence on our gems and need to find out the licenses for all the gems. Having it show up on rubygems.org cuts out the step of having to go to the github repo.

**Comment by rafaelfranca** [comment]
Yes. I agree. I'll add it but it is very unlikely we will have any new
release of this gem, so maybe it will not help too much :(

**Comment by matthewd** [comment]
It's actually already been added: 2cb1576

**Comment by coreyhaines** [comment]
Thanks!! Just doing a long process of due diligence on our application's license compliance. Thanks for the response!
